/**:
  ros__parameters:
    n_drones: 3
    drone:
      speed: 1.0
      acceleration: 1.0
    homebase:
      drone1: [ 0.00,-1.00, 1.00]
      drone2: [ 1.00,-1.00, 1.00]
      drone3: [ 0.00,-2.00, 1.00]
    mission:
      height: 2.0
      distance: 0.5
    common_space:
      height: 3.0
      height_increment: 0.5
    update_plan:
      threshold: 0.8
    battery_per_minute: 5.0
