/**:
  ros__parameters:
    n_drones: 3
    distance:
      trajectory: 1.0
      waypoint: 0.3
    error_limit: 3
    namespace: "/cf"
    drone:
      speed: 1.0
      acceleration: 1.0
    homebase:
      drone1: [-1.00,-1.00, 1.00]
      drone2: [ 0.00,-1.00, 1.00]
      drone3: [ 1.00,-1.00, 1.00]
    mission:
      height: 2.0
      distance: 0.5
    common_space:
      height: 2.5
      height_increment: 0.5
    update_plan:
      threshold: 0.8
    battery_per_minute: 5.0
